

alter table  RESERVA MODIFY  FECHAHORA timestamp;
commit;

-- GRANT SE DEBE EJECUTAR CONECTADO COMO SYS AS SYSDBA --
grant resource, connect, create user, create table,create view to ANIZOOFT;

-- DESPUES DE LOS GRANT SE DEBEN CORRER LOS CREATE VIEW --
CREATE OR REPLACE VIEW VW_ATENCIONES AS
SELECT
0 as ID,
DUEÑO.RUTDUEÑO AS RUTDUEÑO,
DUEÑO.NOMBRE AS NOMBREDUEÑO,
DUEÑO.APELLIDO AS APELLIDODUEÑO,
MASCOTA.IDMASCOTA,
MASCOTA.NOMBRE AS NOMBREMASCOTA,
MASCOTA.RAZA AS RAZAMASCOTA,
ATENCION.FECHAHORA AS FECHAHORAATENCION,
ATENCION.ESTADOATENCION,
PARTICIPACION.RUTEMPLEADO,
EMPLEADO.NOMBRE AS NOMBREEMPLEADO,
EMPLEADO.APELLIDO AS APELLIDOEMPLEADO,
EMPLEADO.CARGO AS CARGOEMPLEADO,
EMPLEADO.ESPECIALIDAD AS ESPECIALIDADEMPLEADO
FROM DUEÑO,MASCOTA,ATENCION,PARTICIPACION,EMPLEADO
WHERE
DUEÑO.RUTDUEÑO = MASCOTA.RUTDUEÑO
AND MASCOTA.IDMASCOTA = ATENCION.IDMASCOTA
AND ATENCION.IDATENCION = PARTICIPACION.IDATENCION
AND PARTICIPACION.RUTEMPLEADO = EMPLEADO.RUTEMPLEADO;

CREATE OR REPLACE VIEW VW_RESUMEN_ATENCIONES AS
SELECT 
0 as ID,
RUTDUEÑO,
NOMBREDUEÑO,
APELLIDODUEÑO,
IDMASCOTA,
NOMBREMASCOTA,
RAZAMASCOTA,
COUNT(1) AS ATENCIONES,
RUTEMPLEADO,
NOMBREEMPLEADO,
APELLIDOEMPLEADO,
CARGOEMPLEADO,
ESPECIALIDADEMPLEADO
FROM VW_ATENCIONES
--WHERE IDMASCOTA = :IDMASCOTA
GROUP BY 
RUTDUEÑO,
NOMBREDUEÑO,
APELLIDODUEÑO,
IDMASCOTA,
NOMBREMASCOTA,
RAZAMASCOTA,
RUTEMPLEADO,
NOMBREEMPLEADO,
APELLIDOEMPLEADO,
CARGOEMPLEADO,
ESPECIALIDADEMPLEADO;

SELECT * FROM VW_ATENCIONES;
SELECT * FROM VW_RESUMEN_ATENCIONES;