

alter table  RESERVA MODIFY  FECHAHORA timestamp;
commit;

CREATE OR REPLACE VIEW RESUMEN_ATENCIONES AS
SELECT 
RUTDUEÑO,
NOMBREDUEÑO,
APELLIDODUEÑO,
IDMASCOTA,
NOMBREMASCOTA,
RAZAMASCOTA,
COUNT(1) AS ATENCIONES,
RUTEMPLEADO,
NOMBREEMPLEADO,
APELLIDOEMPLEADO,
CARGOEMPLEADO,
ESPECIALIDADEMPLEADO
FROM ATENCIONES
--WHERE IDMASCOTA = :IDMASCOTA
GROUP BY 
RUTDUEÑO,
NOMBREDUEÑO,
APELLIDODUEÑO,
IDMASCOTA,
NOMBREMASCOTA,
RAZAMASCOTA,
RUTEMPLEADO,
NOMBREEMPLEADO,
APELLIDOEMPLEADO,
CARGOEMPLEADO,
ESPECIALIDADEMPLEADO;
