-- LMD (30-06-2015)
-- CREACION DE VISTAS --
-- CORRER CON USUARIO SYS CONECTADO COMO SYSDBA
GRANT RESOURCE,CONNECT,DBA,CREATE USER,CREATE VIEW,CREATE TABLE TO ANIZOOFT;

-- CREACION DE VISTA VW_ATENCIONES, EJECUTAR CON USUARIO ANIZOOFT --
CREATE OR REPLACE VIEW VW_ATENCIONES AS
SELECT
0 AS ID,
DUEÑO.RUTDUEÑO AS RUTDUEÑO,
DUEÑO.NOMBRE AS NOMBREDUEÑO,
DUEÑO.APELLIDO AS APELLIDODUEÑO,
MASCOTA.IDMASCOTA,
MASCOTA.NOMBRE AS NOMBREMASCOTA,
MASCOTA.RAZA AS RAZAMASCOTA,
ATENCION.FECHAHORA AS FECHAHORAATENCION,
ATENCION.ESTADOATENCION,
PARTICIPACION.RUTEMPLEADO,
EMPLEADO.NOMBRE AS NOMBREEMPLEADO,
EMPLEADO.APELLIDO AS APELLIDOEMPLEADO,
EMPLEADO.CARGO AS CARGOEMPLEADO,
EMPLEADO.ESPECIALIDAD AS ESPECIALIDADEMPLEADO
FROM DUEÑO,MASCOTA,ATENCION,PARTICIPACION,EMPLEADO
WHERE
DUEÑO.RUTDUEÑO = MASCOTA.RUTDUEÑO
AND MASCOTA.IDMASCOTA = ATENCION.IDMASCOTA
AND ATENCION.IDATENCION = PARTICIPACION.IDATENCION
AND PARTICIPACION.RUTEMPLEADO = EMPLEADO.RUTEMPLEADO;

-- CREACION DE VISTA VW_RESUMEN_ATENCIONES, EJECUTAR CON USUARIO ANIZOOFT --
CREATE OR REPLACE VIEW VW_RESUMEN_ATENCIONES AS
SELECT
ID,
RUTDUEÑO,
NOMBREDUEÑO,
APELLIDODUEÑO,
IDMASCOTA,
NOMBREMASCOTA,
RAZAMASCOTA,
COUNT(1) AS ATENCIONES,
RUTEMPLEADO,
NOMBREEMPLEADO,
APELLIDOEMPLEADO,
CARGOEMPLEADO,
ESPECIALIDADEMPLEADO
FROM VW_ATENCIONES
GROUP BY
ID,
RUTDUEÑO,
NOMBREDUEÑO,
APELLIDODUEÑO,
IDMASCOTA,
NOMBREMASCOTA,
RAZAMASCOTA,
RUTEMPLEADO,
NOMBREEMPLEADO,
APELLIDOEMPLEADO,
CARGOEMPLEADO,
ESPECIALIDADEMPLEADO;

-- VISTAS DETALLE DE ATENCIONES --
SELECT * FROM VW_ATENCIONES;
-- VISTAS RESUMEN DE ATENCIONES --
SELECT * FROM VW_RESUMEN_ATENCIONES;